version: '3.3'

# See: https://blog.manifold.co/building-a-production-grade-container-for-your-static-javascript-application-b2b2eff83fbd
services:
  app:
    image: brainsum/qashot-microsite-fe:1.2.9
    container_name: qashot_microsite_frontend_app
    build:
      context: .
    ports:
    - "${EXPOSED_PORT:-8080}:80"
