version: '2.4'

x-config:
  &config-file-mount
    "./config/config.php:/var/www/html/config.php:ro"

services:
  app:
    image: brainsum/qashot-microsite-fe-app:1.4.0
    volumes:
      - *config-file-mount
      - "source_code:/var/www/html"

  web:
    image: brainsum/qashot-microsite-fe-web:1.1.0
    depends_on:
      - app
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - *config-file-mount
      - "source_code:/var/www/html:ro"

volumes:
  source_code: {}
